### ISSUE TITLE
Build SlackBuilds from Slackware's site

### ISSUE THREAD

**Issue by Xylemon** [dslackw/slpkg#42]
I was wondering if there could be support for building with the SlackBuilds used by the Slackware team? You can find these repos here:

14.1: http://mirrors.slackware.com/slackware/slackware_source/
Current: http://mirrors.slackware.com/slackware/slackware64-current/source/

**Comment by BrentonEarl** [comment]
This would be a great feature to add.  Maybe even add in an editing feature that will allow users to modify the SlackBuild before building it.

**Comment by Xylemon** [comment]
@BrentonEarl That would also be a really nice feature too.

**Comment by dslackw** [comment]
@Xylemon is this useful ?

**Comment by dslackw** [comment]
@BrentonEarl this feature could perhaps be applied to option "-n, --network"

**Comment by dslackw** [comment]
@BrentonEarl I did some test to create custom script via slpkg but shows up that pulls back and does not have great utility since this may be done by hand. So aim slpkg is ease of use which utility to modify a script? Such a possibility serve advanced users who will not get into trouble to make it through slpkg. What do you say ?

**Comment by BrentonEarl** [comment]
You could have have slpkg open up vim or nano to edit the SlackBuild after the SlackBuild in question has been downloaded from the source directory that the user chooses.

Start with a small package as a starting point (something with very little dependencies) for testing and then add code to slpkg later that will go as far as compile the kernel.

I am just not sure how slpkg would handle dependencies for the official Slackware mirrors since there is nothing really tracking dependencies.  It could end up a big mess if someone tries to rebuild say the XOrg server.

**Comment by BrentonEarl** [comment]
Sorry for the late reply.  I have been very busy.

**Comment by BrentonEarl** [comment]
I think it could be done from -n or from -s.  I think that if you add this feature you should definitely consider consolidating the two options because ease of use is in questions when an option does too many things.
```bash
slpkg -s slack -n emacs
```
or maybe by just modifying -n
```bash
slpkg -n emacs -s slack
```

**Comment by dslackw** [comment]
They should be big changes and I don't know if I really deserve. Some tests have shown difficulties in many points.I will leave it little to mature this idea in my mind.

**Comment by BrentonEarl** [comment]
Sounds good.  I will be happy to help with any testing if you do decide to add this functionality.

**Comment by dslackw** [comment]
This seems like feature not as issue. So i close at the moment this issue.

**Comment by Xylemon** [comment]
I hope this gets added one day.
