### ISSUE TITLE
Not able to update with slpkg latest one on current 

### ISSUE THREAD

**Issue by joeshua** [dslackw/slpkg#64]
bash-4.3# slpkg update 

Check and update repositories:

Check repository [slack] ... 
[1/1][ Download ] --> PACKAGES.TXT

--2016-03-23 21:03:18--  http://mirrors.slackware.com/slackware/slackware-14.2/PACKAGES.TXT
Resolving mirrors.slackware.com (mirrors.slackware.com)... 207.223.116.213
Connecting to mirrors.slackware.com (mirrors.slackware.com)|207.223.116.213|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-03-23 21:03:19 ERROR 404: Not Found.

+==============================================================================
| Download 'PACKAGES.TXT' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]? y

[1/1][ Download ] --> CHECKSUMS.md5

--2016-03-23 21:04:18--  http://mirrors.slackware.com/slackware/slackware-14.2/CHECKSUMS.md5
Resolving mirrors.slackware.com (mirrors.slackware.com)... 207.223.116.213
Connecting to mirrors.slackware.com (mirrors.slackware.com)|207.223.116.213|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-03-23 21:04:19 ERROR 404: Not Found.

+==============================================================================
| Download 'CHECKSUMS.md5' file [ FAILED ]
+==============================================================================

Would you like to continue [y/N]? y

[1/1][ Download ] --> PACKAGES.TXT

--2016-03-23 21:04:23--  http://mirrors.slackware.com/slackware/slackware-14.2/extra/PACKAGES.TXT
Resolving mirrors.slackware.com (mirrors.slackware.com)... 207.223.116.213
Connecting to mirrors.slackware.com (mirrors.slackware.com)|207.223.116.213|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-03-23 21:04:23 ERROR 404: Not Found.

**Comment by dslackw** [comment]
Change mirror from /etc/slpkg/slackware-mirrors and try again.

**Comment by joeshua** [comment]
https://github.com/dslackw/slpkg/issues/64#issuecomment-200400209
it works with slackpkg but doent work with slpkg giving above errors

**Comment by dslackw** [comment]
Works for me.

**Comment by mtslzr** [comment]
Sorry for re-opening an issue, but similar problem here. Running a fresh Slackware -current install, and no matter what I do (currently have "current" set in slpkg.conf and haven't touched repos), it fails with a 404 on SlackBuilds.org. Largely because it's trying to grab a sub-folder of 14.2 (like above) and failing.

I noticed the README mentioned setting a VERSION variable, but I've put that in /etc/slpkg/slpkg.conf and passed it on the same line as "slpkg update" and neither makes a difference. Is there something dumb I'm missing for running this with current?
